baseURL: "https://spaceofreasons.netlify.app" 
title: Bob Brandom
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Courses
          url: courses/
          weight: 2 
        - name: Wiki
          url: https://en.wikipedia.org/wiki/Robert_Brandom
          weight: 5

params:
    description: "Distinguished Professor of Philosophy - University of Pittsburgh."
    author: Bob Brandom
    googleAnalyticsID: "G-5KYSW2VWX8"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Prof. Dr. Brandom
          subtitle: "Distinguished Professor of Philosophy - University of Pittsburgh. <br> Fellow, American Academy of Arts and Sciences. <br> Fellow, British Academy."
          imageUrl: "bob-leipzig.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Courses
              url: courses/
            - name: Index
              url: tags/
            - name: Wiki
              url: https://en.wikipedia.org/wiki/Robert_Brandom
            - name: YouTube
              url: https://www.youtube.com/channel/UCbRgL2k8iQ8Sj_sG7wUg7Sg
            - name: Multimedia
              url: video-audio/
              newline: true
            - name: Texts Available for Download
              url: texts/
            - name: Interviews
              url: interviews/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Publications
          url: publications.pdf
        - name: Email
          url: mailto:rbrandom@pitt.edu
        - name: Zoom
          url: https://pitt.zoom.us/my/voice.of.being
        - name: PhilPeople
          url: https://philpeople.org/profiles/robert-brandom
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=rgZKxUEAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/rbrandom

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Bob Brandom"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2